# Generated by Django 3.1.4 on 2020-12-09 12:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='icerik',
            field=ckeditor.fields.RichTextField(verbose_name='upload_to=medyaz'),
        ),
    ]
